Repository RabbyHub/Rabby, pull requests merged in 2024-07, with the labels that each got.

#2367 docs: translate zh-HK
  _raw/locales/zh-HK/messages.json
Labels: external contributor, i18n

#2369 Update defunct, potentially risky QR dependency & Increase QR size
  package.json
Labels: external contributor, dependency changed

#2403 Add NGRAVE ZERO QR-based Hardware Wallet
  _raw/locales/de/messages.json
  _raw/locales/en/messages.json
  _raw/locales/es/messages.json
  _raw/locales/fr-FR/messages.json
  _raw/locales/ja/messages.json
  _raw/locales/pt-BR/messages.json
  _raw/locales/ru/messages.json
  _raw/locales/tr/messages.json
  _raw/locales/ua-UA/messages.json
  _raw/locales/zh-CN/messages.json
  _raw/locales/zh-HK/messages.json
  src/constant/index.ts
  src/ui/assets/walletlogo/ngrave.svg
  src/ui/views/HDManager/HDManager.tsx
Labels: hardware wallet, external contributor
